# Day1
- Write basic code for a neuron
- Matrix operations, represent the NN and flow of data in it
- Loss functions from the mathematical definitions

In [16]:
## inputs, output
# input1: data-->(dataframe, 2D array (list of list), 1D array(vectors) list)
# input2: weights and biases----> weights (list), bias-->number
# activation function----> not a python datastructure

data = [[2,4,6],[3,9,0]]
data_simple = {'row1':[2,4,6],'row2':[3,9,0]}
wts = [6,2,4]
b = 12

def dot(wts,row):
    res = 0
    for weight,inp in zip(wts,row):
        res += weight*inp
    return res

def relu(z):
    return max(0,z)

def sigmoid(z):
    z = -1*z
    exp = 2.71
    return 1/(1+exp**z)

def tanh(z): ## use any library
    exp = 2.71
    N = exp**z-exp**(-(z))
    D = exp**z+exp**(-(z))
    return N/D
    

def neuron(wts,row,bias,activation):
    z = dot(wts,row)+bias
    return activation(z)
    

In [17]:
neuron(wts = wts,row = data_simple['row1'],bias=12,activation = tanh)

1.0

## Forward Pass Implimented using matrix operations

In [23]:
import numpy as np
x1 = 3
x2 = 4
X = np.matrix([[x1],[x2]])
X.shape

(2, 1)

In [24]:
W = np.matrix([[3,4],
               [5,6],
               [7,8],
               [9,10]])
W.shape

(4, 2)

In [25]:
W0 = np.matrix([[5],
               [6],
               [7],
                [8]])

In [26]:
##layer 1 W, W0
W@X+W0

matrix([[30],
        [45],
        [60],
        [75]])

In [27]:
np.matmul(W,X)+W0

matrix([[30],
        [45],
        [60],
        [75]])

In [28]:
Z = W@X+W0

In [29]:
Z

matrix([[30],
        [45],
        [60],
        [75]])

In [30]:
def sigmoid(Z):
    D = 1+np.exp(-Z)
    N = 1
    return N/D

In [31]:
sigmoid(Z)

matrix([[1.],
        [1.],
        [1.],
        [1.]])

In [32]:
Z 
## [[z1],[z2],[z3],[z4]], [f[z1],f[z2]]

matrix([[30],
        [45],
        [60],
        [75]])

In [33]:
V = np.matrix([[2,4,6,8],
               [10,12,14,16]])
V.shape

(2, 4)

In [36]:
V_0 = np.matrix([[7],
              [9]])
V_0.shape

(2, 1)

In [38]:
Z_1 = V@sigmoid(Z)+V_0

In [39]:
Z_1

matrix([[27.],
        [61.]])

In [40]:
Z_1.dtype

dtype('float64')

In [ ]:
def sofrmax():
    pass

In [42]:
class NN():
    def __init__(self,X):
        self.X = X
        self.W = np.matrix([[3,4],
                           [5,6],
                           [7,8],
                           [9,10]])
        self.W0 = np.matrix([[5],
                           [6],
                           [7],
                           [8]])
        self.V = np.matrix([[2,4,6,8],
                           [10,12,14,16]])
        self.V0 = np.matrix([[7],
                              [9]])
    def forward(self):
        Z1 = self.W@self.X+self.W0
        A1 = sigmoid(Z1)
        Z2 = self.V@A1+self.V0
        return Z2

In [43]:
model = NN(X)

In [48]:
model.forward()

matrix([[27.],
        [61.]])