# Text representation
- Bow: Count Matrix
- Bow: Tfidf Matrix
- Extract Keywords
- Find document similarity

In [1]:
### Count Matrix
from sklearn.feature_extraction import text

In [2]:
corpus = ["This is document one",
"This is document two",
"This is document three",
"This is document four"
] ##List of documents

In [3]:
cv=text.CountVectorizer(input = corpus) ## this step only creates a python object and not the matrix

In [4]:
count_matrix=cv.fit_transform(corpus)

In [5]:
count_matrix

<4x7 sparse matrix of type '<class 'numpy.int64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [6]:
count_matrix.toarray()

array([[1, 0, 1, 1, 1, 0, 0],
       [1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 0],
       [1, 1, 1, 0, 1, 0, 0]])

In [7]:
class CountVectorizer():
    def __init__(self,input):
        self.input = input
    def fit_transform(self):
        print("This is fit_transform")

In [10]:
c = CountVectorizer(input=corpus)

In [11]:
c.fit_transform()

This is fit_transform


In [15]:
cv.get_feature_names()

/Users/gunnvantsaini/miniforge3/envs/dl/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['document', 'four', 'is', 'one', 'this', 'three', 'two']

In [13]:
import pandas as pd
pd.DataFrame(count_matrix.toarray(),columns=cv.get_feature_names_out())

document  four  is  one  this  three  two
0         1     0   1    1     1      0    0
1         1     0   1    0     1      0    1
2         1     0   1    0     1      1    0
3         1     1   1    0     1      0    0

In [14]:
import sklearn
sklearn.__version__

'1.0.1'

In [16]:
doc = ['This is document five']

In [18]:
cv.transform(doc).toarray() ### .transform() method will ignore new words in the dataset

array([[1, 0, 1, 0, 1, 0, 0]])

In [19]:
pd.DataFrame(cv.transform(doc).toarray(),columns=cv.get_feature_names_out())

document  four  is  one  this  three  two
0         1     0   1    0     1      0    0

### Class Excercise
- Use this data https://drive.google.com/file/d/11jIco80zFY_nEfVApqo-DD4UXx8J5wGs/view?usp=sharing
- Choose the first 500 rows from the column transcripts
- Create a count matrix for these 500 rows
- Need to create a count matrix using transform() method for rows 501-700 (new data)

In [20]:
path = '/Users/gunnvantsaini/Documents/Data/Kaggle/ted-data/transcripts.csv'
data = pd.read_csv(path)
data.head(2)

transcript  \
0  Good morning. How are you?(Laughter)It's been ...   
1  Thank you so much, Chris. And it's truly a gre...   

                                                 url  
0  https://www.ted.com/talks/ken_robinson_says_sc...  
1  https://www.ted.com/talks/al_gore_on_averting_...

In [21]:
trans = data['transcript'].tolist()[0:500]

In [22]:
cv = text.CountVectorizer(input = trans)
matrix = cv.fit_transform(trans)###

In [23]:
trans_new = data['transcript'].iloc[501:700].tolist()

In [24]:
matrix_new = cv.transform(trans_new) ###

tfidf [link](https://en.wikipedia.org/wiki/Tf–idf)

### Compute tfidf

In [25]:
corpus = ["This is document one",
"This is document two",
"This is document three",
"This is document four"
] ##List of documents

In [26]:
tfidf = text.TfidfVectorizer(input = corpus)

In [27]:
matrix = tfidf.fit_transform(corpus)

In [28]:
matrix

<4x7 sparse matrix of type '<class 'numpy.float64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [31]:
matrix.toarray()

array([[0.38713857, 0.        , 0.38713857, 0.74187006, 0.38713857,
        0.        , 0.        ],
       [0.38713857, 0.        , 0.38713857, 0.        , 0.38713857,
        0.        , 0.74187006],
       [0.38713857, 0.        , 0.38713857, 0.        , 0.38713857,
        0.74187006, 0.        ],
       [0.38713857, 0.74187006, 0.38713857, 0.        , 0.38713857,
        0.        , 0.        ]])

In [32]:
tfidf.get_feature_names_out()

array(['document', 'four', 'is', 'one', 'this', 'three', 'two'],
      dtype=object)

In [33]:
pd.DataFrame(matrix.toarray(),columns=tfidf.get_feature_names_out())

document     four        is      one      this    three      two
0  0.387139  0.00000  0.387139  0.74187  0.387139  0.00000  0.00000
1  0.387139  0.00000  0.387139  0.00000  0.387139  0.00000  0.74187
2  0.387139  0.00000  0.387139  0.00000  0.387139  0.74187  0.00000
3  0.387139  0.74187  0.387139  0.00000  0.387139  0.00000  0.00000

In [37]:
tfidf.transform(doc).toarray()

array([[0.57735027, 0.        , 0.57735027, 0.        , 0.57735027,
        0.        , 0.        ]])

### Class Excercise
- Use this data https://drive.google.com/file/d/11jIco80zFY_nEfVApqo-DD4UXx8J5wGs/view?usp=sharing
- Choose the first 500 rows from the column transcripts
- Create a tfidf matrix for these 500 rows
- Need to create a tfidf matrix using transform() method for rows 501-700 (new data)

In [38]:
data.head(2)

transcript  \
0  Good morning. How are you?(Laughter)It's been ...   
1  Thank you so much, Chris. And it's truly a gre...   

                                                 url  
0  https://www.ted.com/talks/ken_robinson_says_sc...  
1  https://www.ted.com/talks/al_gore_on_averting_...

In [39]:
trans = data['transcript'].tolist()[0:500]
trans_new = data['transcript'].iloc[501:700].tolist()

In [40]:
tfidf = text.TfidfVectorizer(input = trans)
matrix = tfidf.fit_transform(trans)

In [41]:
matrix_new = tfidf.transform(trans_new)

In [42]:
matrix.shape

(500, 31702)

In [43]:
matrix_new.shape

(199, 31702)

In [44]:
matrix.toarray() ## the memory consumption increases drastically (toarray()->dense)

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.0044687 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.0101057 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.06435049, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [45]:
matrix ### remember the locations where there is zero value

<500x31702 sparse matrix of type '<class 'numpy.float64'>'
	with 331767 stored elements in Compressed Sparse Row format>

In [46]:
data.head(2)

transcript  \
0  Good morning. How are you?(Laughter)It's been ...   
1  Thank you so much, Chris. And it's truly a gre...   

                                                 url  
0  https://www.ted.com/talks/ken_robinson_says_sc...  
1  https://www.ted.com/talks/al_gore_on_averting_...

In [47]:
data['url'].iloc[0]

'https://www.ted.com/talks/ken_robinson_says_schools_kill_creativity\n'

In [48]:
data['url'].iloc[1]

'https://www.ted.com/talks/al_gore_on_averting_climate_crisis\n'

In [49]:
data['url'].iloc[2]

'https://www.ted.com/talks/david_pogue_says_simplicity_sells\n'

In [76]:
data.head()

transcript  \
0  Good morning. How are you?(Laughter)It's been ...   
1  Thank you so much, Chris. And it's truly a gre...   
2  (Music: "The Sound of Silence," Simon & Garfun...   
3  If you're here today — and I'm very happy that...   
4  About 10 years ago, I took on the task to teac...   

                                                 url  
0  https://www.ted.com/talks/ken_robinson_says_sc...  
1  https://www.ted.com/talks/al_gore_on_averting_...  
2  https://www.ted.com/talks/david_pogue_says_sim...  
3  https://www.ted.com/talks/majora_carter_s_tale...  
4  https://www.ted.com/talks/hans_rosling_shows_t...

In [52]:
### Can we use tfidf information to extract the important words in each ted-talk?
data.shape

(2467, 2)

## tfidf matrix-->find the top 5 words per doc in each row of the tfidf matrix by their tfidf value

In [54]:
tfidf = text.TfidfVectorizer(input = data['transcript'].tolist(),stop_words='english')
matrix = tfidf.fit_transform(data['transcript'].tolist())

In [55]:
matrix.shape

(2467, 58489)

In [59]:
tfidf_df = pd.DataFrame(matrix.toarray(),columns = tfidf.get_feature_names_out())

In [60]:
tfidf_df.head(2)

00  000  0000  000000004  0000001  000001  00001  000042  0001  0009  ...  \
0  0.0  0.0   0.0        0.0      0.0     0.0    0.0     0.0   0.0   0.0  ...   
1  0.0  0.0   0.0        0.0      0.0     0.0    0.0     0.0   0.0   0.0  ...   

   ālep  čapek  ōfunato  ʾan  ʾilla  ʾilāha   อย  อยman   อร  送你葱  
0   0.0    0.0      0.0  0.0    0.0     0.0  0.0    0.0  0.0  0.0  
1   0.0    0.0      0.0  0.0    0.0     0.0  0.0    0.0  0.0  0.0  

[2 rows x 58489 columns]

In [66]:
tfidf_df.head(2)

00  000  0000  000000004  0000001  000001  00001  000042  0001  0009  ...  \
0  0.0  0.0   0.0        0.0      0.0     0.0    0.0     0.0   0.0   0.0  ...   
1  0.0  0.0   0.0        0.0      0.0     0.0    0.0     0.0   0.0   0.0  ...   

   ālep  čapek  ōfunato  ʾan  ʾilla  ʾilāha   อย  อยman   อร  送你葱  
0   0.0    0.0      0.0  0.0    0.0     0.0  0.0    0.0  0.0  0.0  
1   0.0    0.0      0.0  0.0    0.0     0.0  0.0    0.0  0.0  0.0  

[2 rows x 58489 columns]

In [71]:
tfidf_df.iloc[0].sort_values(ascending=False).head(5).index.tolist()

['education', 'gillian', 'laughter', 'said', 'think']

In [77]:
keywords = []
for i in range(tfidf_df.shape[0]):
    kw=tfidf_df.iloc[i].sort_values(ascending=False).head(5).index.tolist()
    kw = ",".join(kw)
    keywords.append(kw)

In [75]:
",".join(['education', 'gillian', 'laughter', 'said', 'think'])

'education,gillian,laughter,said,think'

In [79]:
data['keywords']=keywords

In [80]:
data.head()

transcript  \
0  Good morning. How are you?(Laughter)It's been ...   
1  Thank you so much, Chris. And it's truly a gre...   
2  (Music: "The Sound of Silence," Simon & Garfun...   
3  If you're here today — and I'm very happy that...   
4  About 10 years ago, I took on the task to teac...   

                                                 url  \
0  https://www.ted.com/talks/ken_robinson_says_sc...   
1  https://www.ted.com/talks/al_gore_on_averting_...   
2  https://www.ted.com/talks/david_pogue_says_sim...   
3  https://www.ted.com/talks/majora_carter_s_tale...   
4  https://www.ted.com/talks/hans_rosling_shows_t...   

                                         keywords  
0           education,gillian,laughter,said,think  
1      tipper,carbon,slideshow,laughter,nashville  
2      microsoft,software,laughter,features,apple  
3  bronx,south,environmental,community,waterfront  
4              countries,data,africa,world,income

In [84]:
data['url'].iloc[0].split("/")[-1].strip()

'ken_robinson_says_schools_kill_creativity'

In [85]:
def get_talk_name(row):
    return row.split("/")[-1].strip()

In [87]:
data['talk_name']=data['url'].map(get_talk_name)

In [88]:
data.head()

transcript  \
0  Good morning. How are you?(Laughter)It's been ...   
1  Thank you so much, Chris. And it's truly a gre...   
2  (Music: "The Sound of Silence," Simon & Garfun...   
3  If you're here today — and I'm very happy that...   
4  About 10 years ago, I took on the task to teac...   

                                                 url  \
0  https://www.ted.com/talks/ken_robinson_says_sc...   
1  https://www.ted.com/talks/al_gore_on_averting_...   
2  https://www.ted.com/talks/david_pogue_says_sim...   
3  https://www.ted.com/talks/majora_carter_s_tale...   
4  https://www.ted.com/talks/hans_rosling_shows_t...   

                                         keywords  \
0           education,gillian,laughter,said,think   
1      tipper,carbon,slideshow,laughter,nashville   
2      microsoft,software,laughter,features,apple   
3  bronx,south,environmental,community,waterfront   
4              countries,data,africa,world,income   

                                           talk_name  
0          ken_robinson_says_schools_kill_creativity  
1                 al_gore_on_averting_climate_crisis  
2                  david_pogue_says_simplicity_sells  
3              majora_carter_s_tale_of_urban_renewal  
4  hans_rosling_shows_the_best_stats_you_ve_ever_...

In [89]:
data['url'].apply(get_talk_name)

0               ken_robinson_says_schools_kill_creativity
1                      al_gore_on_averting_climate_crisis
2                       david_pogue_says_simplicity_sells
3                   majora_carter_s_tale_of_urban_renewal
4       hans_rosling_shows_the_best_stats_you_ve_ever_...
                              ...                        
2462    duarte_geraldino_what_we_re_missing_in_the_deb...
2463    armando_azua_bustos_the_most_martian_place_on_...
2464    radhika_nagpal_what_intelligent_machines_can_l...
2465    theo_e_j_wilson_a_black_man_goes_undercover_in...
2466    karoliina_korppoo_how_a_video_game_might_help_...
Name: url, Length: 2467, dtype: object

In [90]:
### Explore the idea of text similarity and then we will build a reccommendation system, just using tfidf information

## raw_text ---> tfidf matrix ---> cosine similarity matrix ---> data manipulation to find out the similar talks

matrix ## tfidf matrix

<2467x58489 sparse matrix of type '<class 'numpy.float64'>'
	with 1166796 stored elements in Compressed Sparse Row format>

In [91]:
## cosine similarity matrix
from sklearn.metrics.pairwise import cosine_similarity

In [92]:
matrix.shape

(2467, 58489)

In [93]:
sim_matrix = cosine_similarity(matrix)

In [94]:
sim_matrix.shape

(2467, 2467)

In [103]:
sim_matrix[0]

array([1.        , 0.15310631, 0.17626477, ..., 0.07427816, 0.1408498 ,
       0.06360819])

In [119]:
sim_matrix[0].argsort()[-6:-1]

array([1832,  557, 1968,  663, 1421])

In [101]:
import numpy as np
np.array([34,100,56])

array([ 34, 100,  56])

In [102]:
np.array([34,100,56]).argsort()

array([0, 2, 1])

In [104]:
data.head()

transcript  \
0  Good morning. How are you?(Laughter)It's been ...   
1  Thank you so much, Chris. And it's truly a gre...   
2  (Music: "The Sound of Silence," Simon & Garfun...   
3  If you're here today — and I'm very happy that...   
4  About 10 years ago, I took on the task to teac...   

                                                 url  \
0  https://www.ted.com/talks/ken_robinson_says_sc...   
1  https://www.ted.com/talks/al_gore_on_averting_...   
2  https://www.ted.com/talks/david_pogue_says_sim...   
3  https://www.ted.com/talks/majora_carter_s_tale...   
4  https://www.ted.com/talks/hans_rosling_shows_t...   

                                         keywords  \
0           education,gillian,laughter,said,think   
1      tipper,carbon,slideshow,laughter,nashville   
2      microsoft,software,laughter,features,apple   
3  bronx,south,environmental,community,waterfront   
4              countries,data,africa,world,income   

                                           talk_name  
0          ken_robinson_says_schools_kill_creativity  
1                 al_gore_on_averting_climate_crisis  
2                  david_pogue_says_simplicity_sells  
3              majora_carter_s_tale_of_urban_renewal  
4  hans_rosling_shows_the_best_stats_you_ve_ever_...

In [106]:
data.iloc[1421]['talk_name']

'ken_robinson_how_to_escape_education_s_death_valley'

In [107]:
data.iloc[0]['talk_name']

'ken_robinson_says_schools_kill_creativity'

In [108]:
data.iloc[663]['talk_name']

'sir_ken_robinson_bring_on_the_revolution'

In [116]:
data.iloc[sim_matrix[0].argsort()[-6:-1]]['talk_name'].tolist()

['ricardo_semler_how_to_run_a_company_with_almost_no_rules',
 'rory_bremner_s_one_man_world_summit',
 'sakena_yacoobi_how_i_stopped_the_taliban_from_shutting_down_my_school',
 'sir_ken_robinson_bring_on_the_revolution',
 'ken_robinson_how_to_escape_education_s_death_valley']

In [121]:
sim_talks = []
for i in range(sim_matrix.shape[0]):
    idx = sim_matrix[i].argsort()[-6:-1]
    talks = data.iloc[idx]['talk_name'].tolist()
    talks = ",".join(talks)
    sim_talks.append(talks)

In [123]:
data['sim_talks']=sim_talks

In [125]:
data.head(3)

transcript  \
0  Good morning. How are you?(Laughter)It's been ...   
1  Thank you so much, Chris. And it's truly a gre...   
2  (Music: "The Sound of Silence," Simon & Garfun...   

                                                 url  \
0  https://www.ted.com/talks/ken_robinson_says_sc...   
1  https://www.ted.com/talks/al_gore_on_averting_...   
2  https://www.ted.com/talks/david_pogue_says_sim...   

                                     keywords  \
0       education,gillian,laughter,said,think   
1  tipper,carbon,slideshow,laughter,nashville   
2  microsoft,software,laughter,features,apple   

                                   talk_name  \
0  ken_robinson_says_schools_kill_creativity   
1         al_gore_on_averting_climate_crisis   
2          david_pogue_says_simplicity_sells   

                                           sim_talks  
0  ricardo_semler_how_to_run_a_company_with_almos...  
1  david_carson_on_design,rory_bremner_s_one_man_...  
2  john_maeda_on_the_simple_life,rory_bremner_s_o...

In [126]:
sim_matrix.shape[0]

2467

In [148]:
np.array([30,100,56,78,102]).argsort()

array([0, 2, 3, 1, 4])

In [149]:
ar = np.array([30,100,56,78,102])

In [150]:
ar.argpartition(1)

array([0, 2, 1, 3, 4])

In [131]:
?np.argpartition

Signature: np.argpartition(a, kth, axis=-1, kind='introselect', order=None)
Docstring:
Perform an indirect partition along the given axis using the
algorithm specified by the `kind` keyword. It returns an array of
indices of the same shape as `a` that index data along the given
axis in partitioned order.

.. versionadded:: 1.8.0

Parameters
----------
a : array_like
    Array to sort.
kth : int or sequence of ints
    Element index to partition by. The k-th element will be in its
    final sorted position and all smaller elements will be moved
    before it and all larger elements behind it. The order all
    elements in the partitions is undefined. If provided with a
    sequence of k-th it will partition all of them into their sorted
    position at once.
axis : int or None, optional
    Axis along which to sort. The default is -1 (the last axis). If
    None, the flattened array is used.
kind : {'introselect'}, optional
    Selection algorithm. Default is 'introselect'
order : str o