# Text representation
- Bow: Count Matrix
- Bow: Tfidf Matrix
- Extract Keywords
- Find document similarity

In [1]:
### Count Matrix
from sklearn.feature_extraction import text

In [2]:
corpus = ["This is document one",
"This is document two",
"This is document three",
"This is document four"
] ##List of documents

In [3]:
cv=text.CountVectorizer(input = corpus) ## this step only creates a python object and not the matrix

In [4]:
count_matrix=cv.fit_transform(corpus)

In [5]:
count_matrix

<4x7 sparse matrix of type '<class 'numpy.int64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [6]:
count_matrix.toarray()

array([[1, 0, 1, 1, 1, 0, 0],
       [1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 0],
       [1, 1, 1, 0, 1, 0, 0]])

In [7]:
class CountVectorizer():
    def __init__(self,input):
        self.input = input
    def fit_transform(self):
        print("This is fit_transform")

In [10]:
c = CountVectorizer(input=corpus)

In [11]:
c.fit_transform()

This is fit_transform


In [15]:
cv.get_feature_names()

/Users/gunnvantsaini/miniforge3/envs/dl/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['document', 'four', 'is', 'one', 'this', 'three', 'two']

In [13]:
import pandas as pd
pd.DataFrame(count_matrix.toarray(),columns=cv.get_feature_names_out())

document  four  is  one  this  three  two
0         1     0   1    1     1      0    0
1         1     0   1    0     1      0    1
2         1     0   1    0     1      1    0
3         1     1   1    0     1      0    0

In [14]:
import sklearn
sklearn.__version__

'1.0.1'

In [16]:
doc = ['This is document five']

In [18]:
cv.transform(doc).toarray() ### .transform() method will ignore new words in the dataset

array([[1, 0, 1, 0, 1, 0, 0]])

In [19]:
pd.DataFrame(cv.transform(doc).toarray(),columns=cv.get_feature_names_out())

document  four  is  one  this  three  two
0         1     0   1    0     1      0    0

### Class Excercise
- Use this data https://drive.google.com/file/d/11jIco80zFY_nEfVApqo-DD4UXx8J5wGs/view?usp=sharing
- Choose the first 500 rows from the column transcripts
- Create a count matrix for these 500 rows
- Need to create a count matrix using transform() method for rows 501-700 (new data)

In [20]:
path = '/Users/gunnvantsaini/Documents/Data/Kaggle/ted-data/transcripts.csv'
data = pd.read_csv(path)
data.head(2)

transcript  \
0  Good morning. How are you?(Laughter)It's been ...   
1  Thank you so much, Chris. And it's truly a gre...   

                                                 url  
0  https://www.ted.com/talks/ken_robinson_says_sc...  
1  https://www.ted.com/talks/al_gore_on_averting_...

In [21]:
trans = data['transcript'].tolist()[0:500]

In [22]:
cv = text.CountVectorizer(input = trans)
matrix = cv.fit_transform(trans)###

In [23]:
trans_new = data['transcript'].iloc[501:700].tolist()

In [24]:
matrix_new = cv.transform(trans_new) ###

tfidf [link](https://en.wikipedia.org/wiki/Tf–idf)

### Compute tfidf

In [25]:
corpus = ["This is document one",
"This is document two",
"This is document three",
"This is document four"
] ##List of documents

In [26]:
tfidf = text.TfidfVectorizer(input = corpus)

In [27]:
matrix = tfidf.fit_transform(corpus)

In [28]:
matrix

<4x7 sparse matrix of type '<class 'numpy.float64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [31]:
matrix.toarray()

array([[0.38713857, 0.        , 0.38713857, 0.74187006, 0.38713857,
        0.        , 0.        ],
       [0.38713857, 0.        , 0.38713857, 0.        , 0.38713857,
        0.        , 0.74187006],
       [0.38713857, 0.        , 0.38713857, 0.        , 0.38713857,
        0.74187006, 0.        ],
       [0.38713857, 0.74187006, 0.38713857, 0.        , 0.38713857,
        0.        , 0.        ]])

In [32]:
tfidf.get_feature_names_out()

array(['document', 'four', 'is', 'one', 'this', 'three', 'two'],
      dtype=object)

In [33]:
pd.DataFrame(matrix.toarray(),columns=tfidf.get_feature_names_out())

document     four        is      one      this    three      two
0  0.387139  0.00000  0.387139  0.74187  0.387139  0.00000  0.00000
1  0.387139  0.00000  0.387139  0.00000  0.387139  0.00000  0.74187
2  0.387139  0.00000  0.387139  0.00000  0.387139  0.74187  0.00000
3  0.387139  0.74187  0.387139  0.00000  0.387139  0.00000  0.00000

In [37]:
tfidf.transform(doc).toarray()

array([[0.57735027, 0.        , 0.57735027, 0.        , 0.57735027,
        0.        , 0.        ]])

### Class Excercise
- Use this data https://drive.google.com/file/d/11jIco80zFY_nEfVApqo-DD4UXx8J5wGs/view?usp=sharing
- Choose the first 500 rows from the column transcripts
- Create a tfidf matrix for these 500 rows
- Need to create a tfidf matrix using transform() method for rows 501-700 (new data)

In [38]:
data.head(2)

transcript  \
0  Good morning. How are you?(Laughter)It's been ...   
1  Thank you so much, Chris. And it's truly a gre...   

                                                 url  
0  https://www.ted.com/talks/ken_robinson_says_sc...  
1  https://www.ted.com/talks/al_gore_on_averting_...

In [39]:
trans = data['transcript'].tolist()[0:500]
trans_new = data['transcript'].iloc[501:700].tolist()

In [40]:
tfidf = text.TfidfVectorizer(input = trans)
matrix = tfidf.fit_transform(trans)

In [41]:
matrix_new = tfidf.transform(trans_new)

In [42]:
matrix.shape

(500, 31702)

In [43]:
matrix_new.shape

(199, 31702)

In [44]:
matrix.toarray() ## the memory consumption increases drastically (toarray()->dense)

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.0044687 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.0101057 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.06435049, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [45]:
matrix ### remember the locations where there is zero value

<500x31702 sparse matrix of type '<class 'numpy.float64'>'
	with 331767 stored elements in Compressed Sparse Row format>

In [46]:
data.head(2)

transcript  \
0  Good morning. How are you?(Laughter)It's been ...   
1  Thank you so much, Chris. And it's truly a gre...   

                                                 url  
0  https://www.ted.com/talks/ken_robinson_says_sc...  
1  https://www.ted.com/talks/al_gore_on_averting_...

In [47]:
data['url'].iloc[0]

'https://www.ted.com/talks/ken_robinson_says_schools_kill_creativity\n'

In [48]:
data['url'].iloc[1]

'https://www.ted.com/talks/al_gore_on_averting_climate_crisis\n'

In [49]:
data['url'].iloc[2]

'https://www.ted.com/talks/david_pogue_says_simplicity_sells\n'

In [51]:
data['transcript'].iloc[1]

'Thank you so much, Chris. And it\'s truly a great honor to have the opportunity to come to this stage twice; I\'m extremely grateful. I have been blown away by this conference, and I want to thank all of you for the many nice comments about what I had to say the other night. And I say that sincerely, partly because (Mock sob) I need that.(Laughter)Put yourselves in my position.(Laughter)I flew on Air Force Two for eight years.(Laughter)Now I have to take off my shoes or boots to get on an airplane!(Laughter)(Applause)I\'ll tell you one quick story to illustrate what that\'s been like for me.(Laughter)It\'s a true story — every bit of this is true.Soon after Tipper and I left the — (Mock sob) White House —(Laughter)we were driving from our home in Nashville to a little farm we have 50 miles east of Nashville. Driving ourselves.(Laughter)I know it sounds like a little thing to you, but —(Laughter)I looked in the rear-view mirror and all of a sudden it just hit me. There was no motorcade

In [52]:
### Can we use tfidf information to extract the important words in each ted-talk?
data.shape

(2467, 2)

## tfidf matrix-->find the top 5 words per doc in each row of the tfidf matrix by their tfidf value