In [1]:
import pandas as pd
train = pd.read_csv("../codes/data/BBC News Train.csv")
test = pd.read_csv("../codes/data/BBC News Test.csv")

In [2]:
train.head()

ArticleId                                               Text  Category
0       1833  worldcom ex-boss launches defence lawyers defe...  business
1        154  german business confidence slides german busin...  business
2       1101  bbc poll indicates economic gloom citizens in ...  business
3       1976  lifestyle  governs mobile choice  faster  bett...      tech
4        917  enron bosses in $168m payout eighteen former e...  business

In [3]:
test.head()

ArticleId                                               Text
0       1018  qpr keeper day heads for preston queens park r...
1       1319  software watching while you work software that...
2       1138  d arcy injury adds to ireland woe gordon d arc...
3        459  india s reliance family feud heats up the ongo...
4       1020  boro suffer morrison injury blow middlesbrough...

In [4]:
y = train['Category']
X = train['Text']

In [5]:
X.head()

0    worldcom ex-boss launches defence lawyers defe...
1    german business confidence slides german busin...
2    bbc poll indicates economic gloom citizens in ...
3    lifestyle  governs mobile choice  faster  bett...
4    enron bosses in $168m payout eighteen former e...
Name: Text, dtype: object

In [6]:
y.value_counts()

sport            346
business         336
politics         274
entertainment    273
tech             261
Name: Category, dtype: int64

In [8]:
len(y.unique())

5

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
enc = LabelEncoder()

In [12]:
y_train = enc.fit_transform(y)

In [13]:
y_train

array([0, 0, 0, ..., 0, 4, 4])

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y_train,test_size=0.20, random_state=42)

In [16]:
import tensorflow as tf

In [17]:
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

In [19]:
len(X.iloc[0].split(" "))

324

In [20]:
len(X.iloc[1].split(" "))

348

In [21]:
seq_len = 100

In [22]:
vectorizer = TextVectorization(max_tokens = 30000,output_sequence_length=seq_len)

Metal device set to: Apple M1


2022-01-31 16:50:59.865222: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-01-31 16:50:59.865484: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [23]:
text_ds=tf.data.Dataset.from_tensor_slices(X_train).batch(64)

In [24]:
vectorizer.adapt(text_ds) ## fit_transform

2022-01-31 16:52:49.184954: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-01-31 16:52:49.185058: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


In [26]:
report1 = X.iloc[0]

In [27]:
import numpy as np

In [33]:
vectorizer(np.array([[report1]]))

<tf.Tensor: shape=(1, 100), dtype=int64, numpy=
array([[ 1957, 13491,  4445,  1002,  2487,  2404,   198,  1957,   215,
         7582,  2241,    79,     6,  3317,     4,   747,   899,    21,
          355,     6,   148, 15267,    20,    39,    65,  4283, 22228,
         3493,  1957,     8, 21401,     4,  3900,  2187, 10800,  2170,
            3,  9992,  2187,  4777,    22,     2,    51,  2025,   712,
            7,   689,    99,  2868,   650,     3,     2,  2722,     4,
            2,   131,   422,     2,  5883,     4,    33,  5034,  8980,
         2187,   747,    32,  2241,    19,  3234,    29,  1504,     3,
          899,     4,   747,     5,  4956,  2780,  2487,    21,  1134,
           12,    32,  2241, 18511,     6,   376,     4,  2187,  7801,
           22,  1957, 12346,  2708,     3,  3445,  5340,     5,  7263,
         1969]])>

In [31]:
np.array([[report1]])

array([['worldcom ex-boss launches defence lawyers defending former worldcom chief bernie ebbers against a battery of fraud charges have called a company whistleblower as their first witness.  cynthia cooper  worldcom s ex-head of internal accounting  alerted directors to irregular accounting practices at the us telecoms giant in 2002. her warnings led to the collapse of the firm following the discovery of an $11bn (£5.7bn) accounting fraud. mr ebbers has pleaded not guilty to charges of fraud and conspiracy.  prosecution lawyers have argued that mr ebbers orchestrated a series of accounting tricks at worldcom  ordering employees to hide expenses and inflate revenues to meet wall street earnings estimates. but ms cooper  who now runs her own consulting business  told a jury in new york on wednesday that external auditors arthur andersen had approved worldcom s accounting in early 2001 and 2002. she said andersen had given a  green light  to the procedures and practices used by worldcom

In [36]:
len(X.iloc[0].split(" "))

324

In [37]:
len(X.iloc[1].split(" "))

348

In [38]:
sent1 = np.array([["This is a news item"]])

In [39]:
vectorizer(sent1)

<tf.Tensor: shape=(1, 100), dtype=int64, numpy=
array([[  35,   10,    6,  179, 9988,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0]])>

In [40]:
vectorizer.get_vocabulary()[0:10]

['', '[UNK]', 'the', 'to', 'of', 'and', 'a', 'in', 's', 'for']

In [57]:
sent1 = np.array([["He'd is a news item"]])

In [58]:
vectorizer(sent1) ### this can be used as NN layer

<tf.Tensor: shape=(1, 100), dtype=int64, numpy=
array([[   1,   10,    6,  179, 9988,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0]])>

In [59]:
sent1 = np.array([["Cofefe is a news item"]])

In [60]:
vectorizer(sent1)

<tf.Tensor: shape=(1, 100), dtype=int64, numpy=
array([[   1,   10,    6,  179, 9988,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0]])>

In [63]:
from tensorflow import keras

In [66]:
from tensorflow import keras

In [64]:
import tensorflow.keras.layers as layers

In [67]:
len(vectorizer.get_vocabulary())

24922

In [68]:
inputs = keras.Input(shape=(1,),dtype="string")
x = vectorizer(inputs)
x = layers.Embedding(input_dim=24922,output_dim=64)(x) ## (batch_size,seq_len, dim)
x = layers.Flatten()(x) ###(batch_size, seq_len*dim)
x = layers.Dense(64,activation='relu')(x)
x = layers.Dense(5, activation="softmax")(x)

In [69]:
model = tf.keras.Model(inputs,x)

In [70]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
text_vectorization (TextVect (None, 100)               0         
_________________________________________________________________
embedding (Embedding)        (None, 100, 64)           1595008   
_________________________________________________________________
flatten (Flatten)            (None, 6400)              0         
_________________________________________________________________
dense (Dense)                (None, 64)                409664    
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 325       
Total params: 2,004,997
Trainable params: 2,004,997
Non-trainable params: 0
___________________________________________________

In [71]:
model.compile(loss="sparse_categorical_crossentropy",metrics=['acc'])

In [73]:
model.fit(X_train,y_train,batch_size=128,epochs=2,validation_split=0.2)

Epoch 1/2


2022-01-31 17:22:34.879582: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


8/8 [==============================] - 1s 51ms/step - loss: 1.5951 - acc: 0.2770 - val_loss: 1.5667 - val_acc: 0.3891
Epoch 2/2
4/8 [==============>...............] - ETA: 0s - loss: 1.3115 - acc: 0.9766

2022-01-31 17:22:35.529877: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


8/8 [==============================] - 0s 26ms/step - loss: 1.2606 - acc: 0.9601 - val_loss: 1.4443 - val_acc: 0.5146


In [74]:
tf.__version__

'2.7.0'